# Generated by Django 4.2.3 on 2023-07-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=200)),
                ('batting_team', models.CharField(default='', max_length=200)),
                ('bowling_team', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('current_score', models.IntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('wickets', models.IntegerField(default=0)),
                ('last_five', models.IntegerField(default=0)),
                ('pridicted_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='odis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=200)),
                ('batting_team', models.CharField(default='', max_length=200)),
                ('bowling_team', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('current_score', models.IntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('wickets', models.IntegerField(default=0)),
                ('last_ten', models.IntegerField(default=0)),
                ('pridicted_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='t20men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=200)),
                ('batting_team', models.CharField(default='', max_length=200)),
                ('bowling_team', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('current_score', models.IntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('wickets', models.IntegerField(default=0)),
                ('last_five', models.IntegerField(default=0)),
                ('pridicted_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
    ]
